### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by rightfold** [rightfold/dinote#7]
I don't want to think about this.

**EDIT** status update:

 - [x] Authentication
 - [x] Authorization
 - [x] Authentication UI
 - [x] Safe session storage

**Comment by chexxor** [comment]
I'm using stormpath. I have some foreign data types and a few ways to talk to the express middleware. I can share if you want.

**Comment by rightfold** [comment]
Didn't know about that tool 😄 Not using express though, but it seems you don't have to: https://docs.stormpath.com/nodejs/product-guide/latest/quickstart.html

But I still have to do sessions right?

**Comment by rightfold** [comment]
I guess I'll just store sessions in Postgres and use @jshttp/cookie for cookie headers

**Comment by chexxor** [comment]
The express middleware manages the session - it puts it on a cookie. If you write your own, you can probably reference their code: https://github.com/stormpath/express-stormpath

**Comment by chexxor** [comment]
Oh, but i don't know where it stores the sessions. Probably in memory
unless you pass it a handle to a redis-like.
